name: Continuous Integration

on:
  push:
    branches:
      - homologa
      - feature/*
  pull_request:
    branches:
      - homologa
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0' 

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar (Build)
        run: dotnet build --no-restore --configuration Release

      - name: Executar Testes (se houver)
        run: dotnet test --no-build --configuration Release
